import { Meta, StoryObj } from '@storybook/angular';
import { DsMetadataItemComponent } from './ds-metadata-item';

const meta: Meta<DsMetadataItemComponent> = {
  title: 'Primitives/Metadata Item',
  component: DsMetadataItemComponent,
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component: `
A compact component for displaying metadata information with an icon and text. Perfect for status indicators, timestamps, and other supplementary information.

## Features

- **Compact Design**: 20px height with 4px gap between icon and text
- **Consistent Typography**: Uses ui-xs-regular (12px) for text
- **Semantic Colors**: Uses tertiary text color for both icon and text
- **Tooltip Support**: Optional tooltip for additional context
- **Accessible**: Follows WCAG guidelines for color contrast and interactive elements

## Usage Guidelines

1. Use for supplementary information that doesn't require user interaction
2. Keep text content concise and clear
3. Choose appropriate icons that enhance understanding
4. Add tooltips for additional context when needed
5. Group related metadata items with consistent spacing

## Examples

\`\`\`html
<!-- Basic usage -->
<ds-metadata-item
  icon="remixTimeLine"
  value="4 hours ago"
/>

<!-- With tooltip -->
<ds-metadata-item
  icon="remixSurveyLine"
  value="Based on 12 inquiries"
  tooltip="Data collected from recent customer inquiries"
/>

<!-- Multiple items -->
<div style="display: flex; gap: 12px;">
  <ds-metadata-item
    icon="remixSparklingFill"
    value="Important"
  />
  <ds-metadata-item
    icon="remixTimeLine"
    value="4 hours ago"
  />
</div>
\`\`\`
        `,
      },
    },
  },
  tags: ['autodocs'],
  argTypes: {
    icon: {
      control: 'text',
      description: 'The name of the icon to display',
    },
    value: {
      control: 'text',
      description: 'The text value to display',
    },
    tooltip: {
      control: 'text',
      description: 'Optional tooltip text for additional context',
    },
  },
  args: {
    icon: 'remixTimeLine',
    value: '4 hours ago',
  },
};

export default meta;
type Story = StoryObj<DsMetadataItemComponent>;

// Basic Example
export const Basic: Story = {
  args: {
    icon: 'remixTimeLine',
    value: '4 hours ago',
  },
};

// With Tooltip
export const WithTooltip: Story = {
  args: {
    icon: 'remixSurveyLine',
    value: 'Based on 12 inquiries',
    tooltip: 'Data collected from recent customer inquiries',
  },
};

// Common Use Cases
export const CommonUseCases: Story = {
  render: (args) => ({
    props: args,
    template: `
      <div style="display: flex; flex-direction: column; gap: 24px;">
        <!-- Status indicators -->
        <div>
          <h3 style="margin: 0 0 8px 0; font-size: 14px; font-weight: 500;">Status Indicators</h3>
          <div style="display: flex; gap: 12px;">
            <ds-metadata-item
              icon="remixSparklingFill"
              value="Important"
              tooltip="High priority item"
            />
            <ds-metadata-item
              icon="remixCheckLine"
              value="Verified"
              tooltip="Verified by system"
            />
          </div>
        </div>

        <!-- Time-related -->
        <div>
          <h3 style="margin: 0 0 8px 0; font-size: 14px; font-weight: 500;">Time Information</h3>
          <div style="display: flex; gap: 12px;">
            <ds-metadata-item
              icon="remixTimeLine"
              value="4 hours ago"
            />
            <ds-metadata-item
              icon="remixCalendarLine"
              value="Due tomorrow"
              tooltip="Due on March 15, 2024"
            />
          </div>
        </div>

        <!-- Data sources -->
        <div>
          <h3 style="margin: 0 0 8px 0; font-size: 14px; font-weight: 500;">Data Sources</h3>
          <div style="display: flex; gap: 12px;">
            <ds-metadata-item
              icon="remixSurveyLine"
              value="Based on 12 inquiries"
              tooltip="Data from recent customer interactions"
            />
            <ds-metadata-item
              icon="remixDatabaseLine"
              value="System generated"
              tooltip="Generated by AI analysis"
            />
          </div>
        </div>
      </div>
    `,
  }),
  parameters: {
    controls: { disable: true },
  },
};

// Task Example (matches your original design)
export const TaskMetadata: Story = {
  render: (args) => ({
    props: args,
    template: `
      <div style="display: flex; gap: 12px; align-items: center;">
        <ds-metadata-item
          icon="remixSparklingFill"
          value="Important"
          tooltip="High priority task"
        />
        <ds-metadata-item
          icon="remixSurveyLine"
          value="Based on 12 inquiries"
          tooltip="Aggregated from customer feedback"
        />
        <ds-metadata-item
          icon="remixTimeLine"
          value="4 hours ago"
        />
      </div>
    `,
  }),
  parameters: {
    controls: { disable: true },
  },
};
